import './globals.css'
import React from "react";
import ProvidersWrapper from "@/app/ProvidersWrapper";
import HeaderBar from "@/app/HeaderBar";

export const metadata = {
  title: 'my next page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       main layout here
      <ProvidersWrapper>
        <HeaderBar/>
        {children}
      </ProvidersWrapper>
      </body>
    </html>
  )
}
